version: '3.8'

services:
  # Serviço MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-laravel
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - laravel-network

  # Serviço Laravel
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    volumes:
      - .:/laravel
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8000:8000
    networks:
      - laravel-network
    depends_on:
      - mysql
    # Rodar as migrações e seeders ao iniciar o contêiner
    entrypoint: /bin/sh -c "composer install && php artisan migrate:fresh && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-laravel
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - laravel-network
    depends_on:
      - mysql

networks:
  laravel-network:
    driver: bridge
